package org.openmrs.module.icare.store.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import org.openmrs.Location;
import org.openmrs.module.icare.core.Item;
import org.openmrs.module.icare.store.util.Stockable;

import javax.persistence.*;
import java.util.*;

/**
 * StIssueItem generated by hbm2java
 */
@Embeddable
class IssueItemId implements java.io.Serializable {
	
	@ManyToOne
	@JoinColumn(name = "issue_id", nullable = false)
	private Issue issue;
	
	@ManyToOne
	@JoinColumn(name = "item_id", nullable = false)
	private Item item;
	
	public Issue getIssue() {
		return issue;
	}
	
	public void setIssue(Issue issue) {
		this.issue = issue;
	}
	
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
}

@Entity
@Table(name = "st_issue_item")
public class IssueItem implements java.io.Serializable, Stockable {
	
	@EmbeddedId
	private IssueItemId id;
	
	@Column(name = "quantity")
	private Double quantity;
	
	@Column(name = "batch_no", length = 32)
	private String batchNo;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", length = 10)
	private Date expiryDate;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "id")
	//private List<ReceiptItem> receiptItems = new ArrayList<ReceiptItem>(0);
	
	public Double getQuantity() {
		return this.quantity;
	}
	
	@Override
	public Location getLocation() {
		return this.id.getIssue().getIssueingLocation();
	}
	
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}
	
	@Override
	public Item getItem() {
		return this.id.getItem();
	}
	
	public String getBatchNo() {
		return this.batchNo;
	}
	
	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}
	
	public Date getExpiryDate() {
		return this.expiryDate;
	}
	
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}
	
	/*public List<ReceiptItem> getReceiptItems() {
		return receiptItems;
	}
	
	public void setReceiptItems(List<ReceiptItem> receiptItems) {
		this.receiptItems = receiptItems;
	}*/
	
	public void setIssue(Issue issue) {
		if (id == null) {
			this.id = new IssueItemId();
		}
		this.id.setIssue(issue);
	}
	
	public void setItem(Item item) {
		if (id == null) {
			this.id = new IssueItemId();
		}
		this.id.setItem(item);
	}
	
	public Map<String, Object> toMap() {
		Map<String, Object> issueItemObject = new HashMap<String, Object>();
		
		issueItemObject.put("quantity", this.getQuantity());
		issueItemObject.put("batch", this.getBatchNo());
		issueItemObject.put("expiryDate", this.getExpiryDate());
		
		Map<String, Object> itemObject = new HashMap<String, Object>();
		itemObject.put("uuid", this.getId().getItem().getUuid());
		if (this.getId().getItem().getConcept() != null) {
			itemObject.put("display", this.getId().getItem().getConcept().getDisplayString());
		} else if (this.getId().getItem().getDrug() != null) {
			itemObject.put("display", this.getId().getItem().getDrug().getDisplayName());
		}
		issueItemObject.put("item", itemObject);
		
		Map<String, Object> issueObject = new HashMap<String, Object>();
		issueObject.put("uuid", this.getId().getIssue().getUuid());
		
		issueItemObject.put("issue", issueObject);
		
		return issueItemObject;
	}
	
	public IssueItemId getId() {
		return id;
	}
}
