package org.openmrs.module.icare.store.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import org.openmrs.BaseOpenmrsData;
import org.openmrs.DrugOrder;
import org.openmrs.Order;

import javax.persistence.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * StIssueStatus generated by hbm2java
 */
@Entity
@Table(name = "st_order_status")
public class OrderStatus extends BaseOpenmrsData implements java.io.Serializable {
	
	@Id
	@GeneratedValue()
	@Column(name = "order_status_id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	private Order order;
	
	@Column(name = "status", length = 32)
	private OrderStatusCode status;
	
	@Column(name = "remarks", length = 65535)
	private String remarks;
	
	public OrderStatusCode getStatus() {
		return this.status;
	}
	
	public void setStatus(OrderStatusCode status) {
		this.status = status;
	}
	
	public String getRemarks() {
		return this.remarks;
	}
	
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Order getOrder() {
		return order;
	}
	
	public void setOrder(Order order) {
		this.order = order;
	}
	
	public static enum OrderStatusCode {
		EMPTY, ISSUED, CANCELLED, REJECTED, DISPENSED;
		
		private OrderStatusCode() {
		}
	}
	
	public Map<String, Object> toMap() {
		
		Map<String, Object> orderStatusObject = new HashMap<String, Object>();
		
		orderStatusObject.put("uuid", this.getUuid());
		Date date = this.getDateCreated();
		DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
		orderStatusObject.put("created", dateFormat.format(date));
		orderStatusObject.put("remarks", this.getRemarks());
		orderStatusObject.put("status", this.getStatus());
		
		Map<String, Object> creatorObject = new HashMap<String, Object>();
		if (this.getCreator() != null) {
			creatorObject.put("uuid", this.getCreator().getUuid());
			creatorObject.put("display", this.getCreator().getDisplayString());
		}
		orderStatusObject.put("creator", creatorObject);
		
		orderStatusObject.put("order", this.getOrder().getUuid());
		
		return orderStatusObject;
	}
	
	public static OrderStatus fromMap(Map<String, Object> orderStatusMap) {
		
		OrderStatus orderStatus = new OrderStatus();
		orderStatus.setRemarks(orderStatusMap.get("remarks").toString());
		orderStatus.setStatus(OrderStatusCode.valueOf(orderStatusMap.get("status").toString()));
		
		Order order = new Order();
		order.setUuid(((Map) orderStatusMap.get("order")).get("uuid").toString());
		orderStatus.setOrder(order);
		
		return orderStatus;
	}
	
}
