package org.openmrs.module.icare.store.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import org.openmrs.Location;
import org.openmrs.module.icare.core.Item;
import org.openmrs.module.icare.core.JSONConverter;

import javax.persistence.*;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * StStock generated by hbm2java
 */

@Entity
@Table(name = "st_stock")
public class Stock implements java.io.Serializable, JSONConverter {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "stock_id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false)
	private Item item;
	
	@Column(name = "batch", length = 20)
	private String batch;
	
	@Column(name = "expiry_date")
	private Date expiryDate;
	
	@Column(name = "quantity")
	private Double quantity;
	
	@ManyToOne
	@JoinColumn(name = "location_id")
	private Location location;
	
	public String getBatch() {
		return this.batch;
	}
	
	public void setBatch(String batch) {
		this.batch = batch;
	}
	
	public Date getExpiryDate() {
		return this.expiryDate;
	}
	
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}
	
	public Double getQuantity() {
		return this.quantity;
	}
	
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}
	
	public Map<String, Object> toMap() {
		
		Map<String, Object> stockObject = new HashMap<String, Object>();
		
		stockObject.put("batch", this.getBatch());
		
		stockObject.put("expiryDate", this.getExpiryDate());
		
		stockObject.put("quantity", this.getQuantity());
		
		stockObject.put("item", this.getItem().toMap());
		
		Map<String, Object> locationObject = new HashMap<String, Object>();
		if (this.getLocation() != null) {
			locationObject.put("uuid", this.getLocation().getUuid());
			locationObject.put("display", this.getLocation().getDisplayString());
		}
		stockObject.put("location", locationObject);
		
		return stockObject;
	}
	
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public Location getLocation() {
		return location;
	}
	
	public void setLocation(Location location) {
		this.location = location;
	}
}
