package org.openmrs.module.icare.store.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import org.openmrs.BaseOpenmrsData;
import org.openmrs.Location;
import org.openmrs.module.icare.core.Item;
import org.openmrs.Order;
import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * StTransaction generated by hbm2java
 */
@Entity
@Table(name = "st_transaction")
public class Transaction extends BaseOpenmrsData implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transaction_id", unique = true, nullable = false)
	private Integer id;
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	private Order order;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	private Item item;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaction_type_id")
	private TransactionType transactionType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id")
	private Location location;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_location_id")
	private Location sourceLocation;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destination_location_id")
	private Location destinationLocation;
	
	@Column(name = "batch_no")
	private String batchNo;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "expire_date", length = 10)
	private Date expireDate;
	
	@Column(name = "current_quantity")
	private Double currentQuantity;
	
	@Column(name = "previous_quantity")
	private Double previousQuantity;
	
	public Item getItem() {
		return this.item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public String getBatchNo() {
		return this.batchNo;
	}
	
	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}
	
	public Date getExpireDate() {
		return this.expireDate;
	}
	
	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}
	
	public Double getCurrentQuantity() {
		return this.currentQuantity;
	}
	
	public void setCurrentQuantity(Double currentQuantity) {
		this.currentQuantity = currentQuantity;
	}
	
	public Double getPreviousQuantity() {
		return this.previousQuantity;
	}
	
	public void setPreviousQuantity(Double previousQuantity) {
		this.previousQuantity = previousQuantity;
	}
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public TransactionType getTransactionType() {
		return transactionType;
	}
	
	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}
	
	public Location getLocation() {
		return location;
	}
	
	public void setLocation(Location location) {
		this.location = location;
	}
	
	public Location getSourceLocation() {
		return sourceLocation;
	}
	
	public void setSourceLocation(Location sourceLocation) {
		this.sourceLocation = sourceLocation;
	}
	
	public Location getDestinationLocation() {
		return destinationLocation;
	}
	
	public void setDestinationLocation(Location destinationLocation) {
		this.destinationLocation = destinationLocation;
	}
	
	public Order getOrder() {
		return order;
	}
	
	public void setOrder(Order order) {
		this.order = order;
	}
}
