package org.openmrs.module.icare.laboratory.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import org.openmrs.module.icare.core.Item;

import javax.persistence.*;

/**
 * LbDispensableItem generated by hbm2java
 */
//@Entity
//@Table(name = "lb_dispensable_item")
public class DispensableItem implements java.io.Serializable {
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	private Item item;
	
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
}
