package org.openmrs.module.icare.laboratory.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * LbStorageType generated by hbm2java
 */
@Entity
@Table(name = "lb_storage_type")
public class StorageType implements java.io.Serializable {
	
	@Id
	@GeneratedValue()
	@Column(name = "storage_type_id", unique = true, nullable = false)
	private int id;
	
	@Column(name = "name", length = 32)
	private String name;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storageType")
	private List<Storage> storages = new ArrayList<Storage>(0);
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public List<Storage> getStorages() {
		return storages;
	}
	
	public void setStorages(List<Storage> storages) {
		this.storages = storages;
	}
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
}
