package org.openmrs.module.icare.laboratory.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * LbStorage generated by hbm2java
 */
@Entity
@Table(name = "lb_storage")
public class Storage implements java.io.Serializable {
	
	@Id
	@GeneratedValue()
	@Column(name = "storage_id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_type_id", nullable = false)
	private StorageType storageType;
	
	@Column(name = "name", length = 32)
	private String name;
	
	@Column(name = "capacity")
	private Integer capacity;
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Integer getCapacity() {
		return this.capacity;
	}
	
	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public StorageType getStorageType() {
		return storageType;
	}
	
	public void setStorageType(StorageType storageType) {
		this.storageType = storageType;
	}
}
