package org.openmrs.module.icare.billing.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import com.fasterxml.jackson.annotation.JsonInclude;
import org.openmrs.module.icare.core.Item;

import javax.persistence.*;
import java.util.HashMap;
import java.util.Map;

@Embeddable
class DiscountInvoiceItemID implements java.io.Serializable {
	
	@ManyToOne
	@JoinColumn(name = "discount_id")
	private Discount discount;
	
	@ManyToOne
	@JoinColumn(name = "invoice_id")
	private Invoice invoice;
	
	@ManyToOne
	@JoinColumn(name = "item_id")
	private Item item;
	
	public Discount getDiscount() {
		return discount;
	}
	
	public void setDiscount(Discount discount) {
		this.discount = discount;
	}
	
	public Invoice getInvoice() {
		return invoice;
	}
	
	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}
	
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
}

/**
 * BlDiscountInvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "bl_discount_invoice_item")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DiscountInvoiceItem implements java.io.Serializable {
	
	@EmbeddedId
	private DiscountInvoiceItemID id;
	
	@Column(name = "amount", precision = 22, scale = 0)
	private Double amount;
	
	public Double getAmount() {
		return amount;
	}
	
	public void setAmount(Double amount) {
		this.amount = amount;
	}
	
	public DiscountInvoiceItemID getId() {
		return id;
	}
	
	public void setId(DiscountInvoiceItemID id) {
		this.id = id;
	}
	
	public Invoice getInvoice() {
		if (id == null) {
			id = new DiscountInvoiceItemID();
		}
		return id.getInvoice();
	}
	
	public void setInvoice(Invoice invoice) {
		if (id == null) {
			id = new DiscountInvoiceItemID();
		}
		this.id.setInvoice(invoice);
	}
	
	public Discount getDiscount() {
		return this.id.getDiscount();
	}
	
	public void setDiscount(Discount discount) {
		if (id == null) {
			id = new DiscountInvoiceItemID();
		}
		this.id.setDiscount(discount);
	}
	
	public Item getItem() {
		return this.id.getItem();
	}
	
	public void setItem(Item item) {
		if (id == null) {
			id = new DiscountInvoiceItemID();
		}
		this.id.setItem(item);
	}
	
	public Map<String, Object> getMap() {
		Map<String, Object> itemMap = new HashMap<String, Object>();
		itemMap.put("amount", this.getAmount());
		Map<String, Object> discountItemInvoiceObject = new HashMap<String, Object>();
		discountItemInvoiceObject.put("uuid", this.getInvoice().getUuid());
		itemMap.put("invoice", discountItemInvoiceObject);
		
		Map<String, Object> discountItemItemObject = new HashMap<String, Object>();
		discountItemItemObject.put("uuid", this.getItem().getUuid());
		if (this.getItem().getConcept() != null) {
			discountItemItemObject.put("name", this.getItem().getConcept().getDisplayString());
		}
		if (this.getItem().getDrug() != null) {
			discountItemItemObject.put("name", this.getItem().getDrug().getDisplayName());
		}
		itemMap.put("item", discountItemItemObject);
		return itemMap;
	}
}
