package org.openmrs.module.icare.billing.models;

// Generated Oct 7, 2020 12:48:40 PM by Hibernate Tools 5.2.10.Final

import com.fasterxml.jackson.annotation.JsonInclude;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.openmrs.Order;
import org.openmrs.module.icare.core.Item;

import javax.persistence.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@Embeddable
class InvoiceItemID implements java.io.Serializable {
	
	@ManyToOne
	@JoinColumn(name = "invoice_id")
	private Invoice invoice;
	
	@ManyToOne
	@JoinColumn(name = "item_id")
	private Item item;
	
	@OneToOne
	@JoinColumn(name = "order_id")
	@JsonIgnore
	private Order order;
	
	public Invoice getInvoice() {
		return invoice;
	}
	
	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}
	
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	public Order getOrder() {
		return order;
	}
	
	public void setOrder(Order order) {
		this.order = order;
	}
}

/**
 * BlInvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "bl_invoice_item")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InvoiceItem implements java.io.Serializable {
	
	@EmbeddedId
	@JsonIgnore
	private InvoiceItemID id;
	
	@Column(name = "quantity", nullable = false)
	private Double quantity;
	
	@Column(name = "price", nullable = false, precision = 10, scale = 0)
	private Double price;
	
	public InvoiceItem() {
		
	}
	
	public Double getQuantity() {
		return this.quantity;
	}
	
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}
	
	public Double getPrice() {
		return this.price;
	}
	
	public void setPrice(Double price) {
		this.price = price;
	}
	
	public InvoiceItemID getId() {
		return id;
	}
	
	public void setId(InvoiceItemID id) {
		this.id = id;
	}
	
	public Invoice getInvoice() {
		return id.getInvoice();
	}
	
	public void setInvoice(Invoice invoice) {
		if (id == null) {
			id = new InvoiceItemID();
		}
		id.setInvoice(invoice);
	}
	
	public Item getItem() {
		return id.getItem();
	}
	
	public void setItem(Item item) {
		if (id == null) {
			id = new InvoiceItemID();
		}
		id.setItem(item);
	}
	
	public Order getOrder() {
		return id.getOrder();
	}
	
	public void setOrder(Order order) {
		if (id == null) {
			id = new InvoiceItemID();
		}
		id.setOrder(order);
	}
	
	public Map<String, Object> getMap() {
		Map<String, Object> itemMap = new HashMap<String, Object>();
		itemMap.put("price", this.getPrice());
		itemMap.put("quantity", this.getQuantity());
		Map<String, Object> discountItemInvoiceObject = new HashMap<String, Object>();
		discountItemInvoiceObject.put("uuid", this.getInvoice().getUuid());
		itemMap.put("invoice", discountItemInvoiceObject);
		
		Map<String, Object> orderObject = new HashMap<String, Object>();
		orderObject.put("uuid", this.getOrder().getUuid());
		itemMap.put("order", orderObject);
		
		Map<String, Object> discountItemItemObject = new HashMap<String, Object>();
		discountItemItemObject.put("uuid", this.getItem().getUuid());
		if (this.getItem().getConcept() != null) {
			
			Map<String, Object> conceptObject = new HashMap<String, Object>();
			conceptObject.put("name", this.getItem().getConcept().getDisplayString());
			conceptObject.put("uuid", this.getItem().getConcept().getUuid());
			
			discountItemItemObject.put("concept", conceptObject);
			
		}
		if (this.getItem().getDrug() != null) {
			discountItemItemObject.put("name", this.getItem().getDrug().getDisplayName());
		}
		itemMap.put("item", discountItemItemObject);
		return itemMap;
	}
	
	public String toString() {
		return "InvoiceItem[Order:" + this.getId().getOrder() + "| Item:" + this.getId().getItem() + "| Q:"
		        + this.getQuantity() + "| P:" + this.getPrice() + "]";
	}
	
	@Override
	public int hashCode() {
		return Objects.hash(this.toString());
	}
	
	public Map<String,Object> toMap() {
		Map<String,Object> invoiceItemMap = new HashMap<>();
		invoiceItemMap.put("quantity", this.getQuantity());
		invoiceItemMap.put("price", this.getPrice());

		Map<String,Object> orderMap = new HashMap<>();
		orderMap.put("uuid",this.getId().getOrder().getUuid());
		invoiceItemMap.put("order", orderMap);

		Map<String,Object> itemMap = new HashMap<>();
		itemMap.put("uuid",this.getId().getItem().getUuid());
		itemMap.put("display",this.getId().getItem().getDisplayString());
		invoiceItemMap.put("item", itemMap);

		invoiceItemMap.put("invoice", this.getInvoice().toMap());
		return invoiceItemMap;
	}
}
